version: '2.1'

services:
  sos-page:
    image: ok-diet
    container_name: ok-diet
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Tokyo
    build: .
    ports:
      - "5000:5000"
    command: ["pipenv", "run", "web"]
